
name: Deploy to media.hikkary.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MEDIA_SSH }}

      - name: Deploy update to server
        run: |
          ssh hikkary@media.hikkary.com <<'ENDSSH'
          cd /home/hikkary/projet/ground-floor-api
          git stash
          git pull
          yarn
          yarn build
          cd ~
          pm2 restart all
          ENDSSH
